<?php

if( function_exists('acf_add_options_page') ) {

	acf_add_options_page([
		'menu_title' 	=> 'Šablona',
		'menu_slug' 	=> 'theme-settings',
		'capability'	=> 'edit_posts',
		'position'    => 61,
		'icon_url'    => 'dashicons-welcome-widgets-menus',
	]);

	acf_add_options_sub_page([
		'page_title' 	=> 'Obecná správa',
		'menu_title' 	=> 'Obecné',
		'parent_slug' => 'theme-settings',
	]);

	acf_add_options_sub_page([
		'page_title' 	=> 'Nastavení domovské stránky',
		'menu_title' 	=> 'Homepage',
		'parent_slug' => 'theme-settings',
	]);

	acf_add_options_sub_page([
		'page_title' 	=> 'Nastavení seznamu e-shopů',
		'menu_title' 	=> 'Seznam e-shopů',
		'parent_slug' => 'theme-settings',
	]);

	acf_add_options_sub_page([
		'page_title' 	=> 'Nastavení mailingu',
		'menu_title' 	=> 'Mailing',
		'parent_slug' => 'theme-settings',
	]);

}

add_action( 'acf/init', function () {

  if ( ! current_user_can( 'subscriber' ) ):

    acf_add_local_field_group(array(
      'key' => 'group_5fbe3ae73c396',
      'title' => 'Pokročilé nastavení (admin only)',
      'fields' => array(
        array(
          'key' => 'field_5a8dcfcaccf40',
          'label' => 'Interní poznámka',
          'name' => 'internal_note',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => '',
        ),
        array(
          'key' => 'field_5fbe3b2726ed2',
          'label' => 'Skrýt v náhledu e-shopu',
          'name' => 'urlbox_hide_selector',
          'type' => 'text',
          'instructions' => 'Zadejte CSS selektor elementu, který má být skrytý při vytváření náhledu e-shopu. Více selektorů oddělte čárko. Např. <code>.popup,.popup-container</code>',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_605c5c1818d73',
          'label' => 'Zobrazit placeholder',
          'name' => 'show_placeholder',
          'type' => 'true_false',
          'instructions' => 'Zobrazit placeholder s logem Eshopiště místo screenshotu e-shopu. Vhodné např. pokud se screenshot nevygeneruje nebo na doméně není možné udělat reprezentativní screenshot.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array(
          'key' => 'field_62136ae6dd3f2',
          'label' => 'Vlastní placeholder',
          'name' => 'custom_placeholder',
          'type' => 'image',
          'instructions' => 'Nahrát vlastní placeholder e-shopu, např. logo nebo vlastní screenshot. Ideální velikost 940x535.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_605c5c1818d73',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'medium',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'eshop',
          ),
        ),
      ),
      'menu_order' => 100,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
    ));
    
  endif;

  acf_add_local_field_group(array(
    'key' => 'group_5a7c42351619c',
    'title' => 'Kategorie',
    'fields' => array(
      array(
        'key' => 'field_5a7c450106a90',
        'label' => 'Obrázek',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5a7c49eb5a28d',
        'label' => 'Titulek v náhledu',
        'name' => 'thumbnail_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'taxonomy',
          'operator' => '==',
          'value' => 'eshop_category',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a8d9fb3a7899',
    'title' => 'Nabídka',
    'fields' => array(
      array(
        'key' => 'field_5a8d9fbeccf3f',
        'label' => 'E-mail',
        'name' => 'email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_5a8d9fcdccf40',
        'label' => 'Zpráva',
        'name' => 'message',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_5a8d9fdcccf41',
        'label' => 'E-shop',
        'name' => 'eshop',
        'type' => 'post_object',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'eshop',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'eshop_bid',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a81a23ae159a',
    'title' => 'Nastavení homepage',
    'fields' => array(
      array(
        'key' => 'field_5a9405e5d580e',
        'label' => 'Claim',
        'name' => 'homepage_claim',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a8882e6a5b27',
        'label' => 'Kategorie č. 1 v sekci s eshopy na prodej',
        'name' => 'homepage_category_for_sale_1',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'eshop_category',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5a8884c330396',
        'label' => 'Kategorie č. 2 v sekci s eshopy na prodej',
        'name' => 'homepage_category_for_sale_2',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'eshop_category',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5a8884da30397',
        'label' => 'Kategorie v sekci s eshopy se zájmem o investici',
        'name' => 'homepage_category_for_invest',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'eshop_category',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5a81a26251b2f',
        'label' => 'Rady do začátku',
        'name' => 'homepage_posts_ids',
        'type' => 'relationship',
        'instructions' => 'Zvolte prosím až 3 články',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'page',
          1 => 'post',
        ),
        'taxonomy' => array(
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => 3,
        'return_format' => 'id',
      ),
      array(
        'key' => 'field_5a81a44aa2ab6',
        'label' => 'Komu jsme už pomohli',
        'name' => 'homepage_testimonial',
        'type' => 'repeater',
        'instructions' => 'Napište prosím 3 doporučení',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 3,
        'layout' => 'row',
        'button_label' => 'Přidat doporučení',
        'sub_fields' => array(
          array(
            'key' => 'field_5a81a631cec60',
            'label' => 'Jméno',
            'name' => 'name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5a81a63acec61',
            'label' => 'Fotografie',
            'name' => 'image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5a81a646cec62',
            'label' => 'Pozice',
            'name' => 'position',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5a81a651cec63',
            'label' => 'Text doporučení',
            'name' => 'text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'wpautop',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-homepage',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a971a73dc55a',
    'title' => 'Nastavení mailingu',
    'fields' => array(
      array(
        'key' => 'field_5a971a8cbed13',
        'label' => 'Odesílatel e-mailů',
        'name' => 'email_from',
        'type' => 'text',
        'instructions' => 'Ve tvaru "Jméno &lt;email&gt;"',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e1497',
        'label' => 'Předmět e-mailu se zprávou pro velkoobchod',
        'name' => 'wholesaler_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e149e',
        'label' => 'Tělo e-mailu se zprávou pro velkoobchod',
        'name' => 'wholesaler_email_body',
        'type' => 'textarea',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' a %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 12,
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_5a971a73e14a5',
        'label' => 'Předmět potvrzovacího e-mailu pro odesílatele',
        'name' => 'retailer_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e14ac',
        'label' => 'Tělo potvrzovacího e-mailu pro odesílatele',
        'name' => 'retailer_email_body',
        'type' => 'textarea',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' a %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 12,
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_5a98129ba2bfb',
        'label' => 'Předmět e-mailu s pro nového uživatele',
        'name' => 'welcome_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a9812a2a2bfc',
        'label' => 'Tělo e-mailu pro nového uživatele',
        'name' => 'welcome_email_body',
        'type' => 'textarea',
        'instructions' => 'Je možné využít následující proměnné: %username% a %set_password_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 12,
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_5b802e5b11ddf',
        'label' => 'Předmět e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b802e8711de0',
        'label' => 'Tělo e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_body',
        'type' => 'textarea',
        'instructions' => 'Je možné využít následující proměnné: %eshop_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 12,
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_5b802ebc11de1',
        'label' => 'Příjemci e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_recipients',
        'type' => 'user',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'role' => '',
        'allow_null' => 0,
        'multiple' => 1,
        'return_format' => 'array',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-mailing',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a844aa82bdac',
    'title' => 'Nastavení seznamu e-shopů',
    'fields' => array(
      array(
        'key' => 'field_5a844b007e55b',
        'label' => 'Článek v banneru',
        'name' => 'archive_post_id',
        'type' => 'post_object',
        'instructions' => 'Článek se zobrazí uprostřed seznamu s e-shopy.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'post',
          1 => 'page',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'id',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5a844ad27e55a',
        'label' => 'SEO text',
        'name' => 'archive_seo_text',
        'type' => 'textarea',
        'instructions' => 'Text se zobrazí pod seznamem s e-shopy.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-seznam-e-shopu',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a82a5af5362c',
    'title' => 'Obecné nastavení',
    'fields' => array(
      array(
        'key' => 'field_5a95811385735',
        'label' => 'Open graph obrázek',
        'name' => 'opengraph_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5a82a5bbc5a37',
        'label' => 'Text v patičce',
        'name' => 'footer_text',
        'type' => 'wysiwyg',
        'instructions' => 'Text se zobrazí v patičce pod logem Shoptet.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a887feeb8090',
        'label' => 'Text na stránce 404',
        'name' => 'not_found_text',
        'type' => 'wysiwyg',
        'instructions' => 'Text se zobrazí na stránce 404.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a9dca47ea91e',
        'label' => 'Doba expirace e-shopu',
        'name' => 'eshop_expiration_time',
        'type' => 'number',
        'instructions' => 'Doba, po které bude publikovaný e-shop automaticky skryt',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'dnů',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a9dcae9ccdb7',
        'label' => 'Maximální stáří nového e-shopu',
        'name' => 'eshop_is_new_interval',
        'type' => 'number',
        'instructions' => 'Doba, po kterou bude e-shop označený přívlaskem „nový“',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'dnů',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-obecne',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a43a71ba50b1',
    'title' => 'Typ nabídky',
    'fields' => array(
      array(
        'key' => 'field_5a43a738c05b6',
        'label' => 'Mám zájem o',
        'name' => 'type',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          0 => 'Prodej mého e-shopu',
          1 => 'Půjčku',
          2 => 'Společníka/Investora',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => '',
        'layout' => 'vertical',
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_5a43a844c05b7',
        'label' => 'Cena',
        'name' => 'price',
        'type' => 'number',
        'instructions' => 'Uveďte za jakou cenu, bez DPH, chcete váš e-shop prodat. Tipy na určení výše požadované částky naleznete v <a href="https://www.eshopiste.cz/jak-spravne-prodat-e-shop" target="_blank">našem návodu</a>.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5a43a738c05b6',
              'operator' => '==',
              'value' => '0',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a43a899c05b8',
        'label' => 'Půjčka',
        'name' => 'price',
        'type' => 'number',
        'instructions' => 'Výše vámi požadované půjčky.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5a43a738c05b6',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a7ca84c764de',
        'label' => 'Investice',
        'name' => 'price',
        'type' => 'number',
        'instructions' => 'Jak velkou částku od investora požadujete.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5a43a738c05b6',
              'operator' => '==',
              'value' => '2',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a43a8cdc05b9',
        'label' => 'Doba splácení',
        'name' => 'repayment_period',
        'type' => 'number',
        'instructions' => 'Po kolika měsících hodláte půjčku vrátit.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5a43a738c05b6',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'měsíce',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a43a925c05ba',
        'label' => 'Nabízený úrok',
        'name' => 'interest_rate',
        'type' => 'number',
        'instructions' => 'Vámi navrhované roční zůročení půjčky.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5a43a738c05b6',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '%',
        'min' => 0,
        'max' => 100,
        'step' => '',
      ),
      array(
        'key' => 'field_5a43ae0937920',
        'label' => 'Nabízený podíl',
        'name' => 'share',
        'type' => 'number',
        'instructions' => 'Jaký procentuální vlastnický podíl ve firmě nabízíte.',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5a43a738c05b6',
              'operator' => '==',
              'value' => '2',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '%',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'eshop',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a4395c1c94e0',
    'title' => 'Základní informace',
    'fields' => array(
      array(
        'key' => 'field_5a4395df32f5e',
        'label' => 'URL e-shopu',
        'name' => 'eshop_url',
        'type' => 'url',
        'instructions' => 'Adresa vašeho e-shopu. Např. „https://www.shoptet.cz“',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5a7ca88485c0f',
        'label' => 'E-shop na Shoptetu',
        'name' => 'is_shoptet',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'E-shop beží na platformě Shoptet',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5a43963c32f60',
        'label' => 'Majitel e-shopu',
        'name' => 'eshop_owner',
        'type' => 'text',
        'instructions' => 'Název právního subjektu vlastnící e-shop. Např. „Shoptet s.r.o.“',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a43965a32f61',
        'label' => 'IČ majitele e-shopu',
        'name' => 'eshop_owner_cin',
        'type' => 'text',
        'instructions' => 'Např. „28935675“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a4396e532f62',
        'label' => 'Vaše jméno',
        'name' => 'seller_name',
        'type' => 'text',
        'instructions' => 'Jméno vás jako fyzické osoby, která může transakci nabídnout a zrealizovat. Např. „Miroslav Uďan“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a43971632f63',
        'label' => 'Vaše pozice ve firmě',
        'name' => 'seller_position',
        'type' => 'text',
        'instructions' => 'Název vaši pozice v oranizační struktuře firmy. Např. „Jednatel“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a43973a32f64',
        'label' => 'Kontaktní e-mail',
        'name' => 'contact_email',
        'type' => 'email',
        'instructions' => 'E-mail na který vám budou moct být zasílané nabídky od investorů. Např. „info@shoptet.cz“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_5a43c005d0c52',
        'label' => 'Kategorie e-shopu',
        'name' => 'category',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte si kategorii do které váš e-shop spadá.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'taxonomy' => 'eshop_category',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 1,
        'load_terms' => 1,
        'return_format' => 'object',
        'multiple' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'eshop',
        ),
      ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5a43ab89519ef',
    'title' => 'Podrobné informace',
    'fields' => array(
      array(
        'key' => 'field_5a43bbb30ea1f',
        'label' => 'Popište váš e-shop',
        'name' => 'description',
        'type' => 'wysiwyg',
        'instructions' => 'Rozepište se o historii a duležitých meznících vašeho e-shopu. Vše co může investorům získat lepší vhled na váš byznys.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a43bbdb0ea20',
        'label' => 'Důvod nabídky',
        'name' => 'reason',
        'type' => 'textarea',
        'instructions' => 'Napište proč jste se rozhodli tuto nabídku zveřejnit a získat požadovanou protihodnotu.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_5a43bc090ea21',
        'label' => 'Krátké info přímo o vás',
        'name' => 'info_about_you',
        'type' => 'textarea',
        'instructions' => 'Několik řádek o vás jako zástupci e-shopu. Bude zveřejněno u kontaktního formuláře.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_5a43bc2f8e703',
        'label' => 'Facebook e-shopu',
        'name' => 'facebook',
        'type' => 'url',
        'instructions' => 'Adresa na váš případný Facebook profil. Např. „https://www.facebook.com/shoptet/“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5e567026f0fa0',
        'label' => 'Instagram e-shopu',
        'name' => 'instagram',
        'type' => 'url',
        'instructions' => 'Adresa na váš případný Instagram profil. Např. „https://www.instagram.com/shoptet/“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5a43bc448e704',
        'label' => 'Twitter e-shopu',
        'name' => 'twitter',
        'type' => 'url',
        'instructions' => 'Adresa na váš případný Twitter profil. Např. „https://twitter.com/shoptet“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-medium',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5a43bc5d8e705',
        'label' => 'Obrat za posledních 12 měsíců',
        'name' => 'turnover',
        'type' => 'number',
        'instructions' => 'Celkový obrat e-shopu za posledních 12 měsíců, včetně DPH.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a43bc878e706',
        'label' => 'Návštěvnost za posledních 12 měsíců',
        'name' => 'traffic',
        'type' => 'number',
        'instructions' => 'Celková návštěvnost za posledních 12 měsíců. Jako metriku použijte data z Google Analytics.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => 'UN',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a43bcdc8e707',
        'label' => 'EBITDA za poslední rok',
        'name' => 'ebitda',
        'type' => 'number',
        'instructions' => 'Zisk vašeho e-shopu před započtením úroků, daní a odpisů. Slouží jako indikátor vaší provozní výkonnosti.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5a43bd098e708',
        'label' => 'Stáří e-shopu',
        'name' => 'age',
        'type' => 'select',
        'instructions' => 'Kolik let je váš e-shop už v provozu?',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => 'acf-field-small',
          'id' => '',
        ),
        'choices' => array(
          0 => '0 až 1 rok',
          1 => '1 až 2 roky',
          2 => '2 až 3 roky',
          3 => '3 až 4 roky',
          4 => '4 až 5 let',
          5 => '5 let a více',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5a43ab8bd9532',
        'label' => 'Co je předmětem nabídky?',
        'name' => 'offered_items',
        'type' => 'checkbox',
        'instructions' => 'Definujte co vše je součástí balíčku, který nabízíte investorům.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'Doména' => 'Doména',
          'Skladové zásoby' => 'Skladové zásoby',
          'Kamenná prodejna' => 'Kamenná prodejna',
          'Balící materiál' => 'Balící materiál',
          'Zaměstnanci' => 'Zaměstnanci',
          'Profily na sociálních sítích' => 'Profily na sociálních sítích',
          'Kontakty na dodavatele' => 'Kontakty na dodavatele',
          'Databáze zákazníků' => 'Databáze zákazníků',
          'Zaučení' => 'Zaučení',
          'Ochranná známka' => 'Ochranná známka',
          'Logo' => 'Logo',
        ),
        'allow_custom' => 1,
        'save_custom' => 0,
        'default_value' => array(
        ),
        'layout' => 'horizontal',
        'toggle' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_5a43bdc082225',
        'label' => 'Historický obrat',
        'name' => 'turnover_history',
        'type' => 'repeater',
        'instructions' => 'Uveďte obrat vaší firmy po jednotlivých letech (začněte od starších let k novějším). Maximálně za posledních 10 let.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Přidat rok',
        'sub_fields' => array(
          array(
            'key' => 'field_5a43bdf082226',
            'label' => 'Rok',
            'name' => 'year',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Rok',
            'prepend' => '',
            'append' => '',
            'min' => 1990,
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_5a43be6282227',
            'label' => 'Obrat',
            'name' => 'turnover',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Obrat',
            'prepend' => '',
            'append' => 'Kč',
            'min' => 0,
            'max' => '',
            'step' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5a43bf1894815',
        'label' => 'Historická návštěvnost',
        'name' => 'traffic_history',
        'type' => 'repeater',
        'instructions' => 'Uveďte návštěvnost (můžete čerpat např. z Google Analytics) vašeho e-shopu po jednotlivých letech (začněte od starších let k novějším). Maximálně za posledních 10 let.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Přidat rok',
        'sub_fields' => array(
          array(
            'key' => 'field_5a43bf1894816',
            'label' => 'Rok',
            'name' => 'year',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Rok',
            'prepend' => '',
            'append' => '',
            'min' => 1990,
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_5a43bf1894817',
            'label' => 'Návštěvnost',
            'name' => 'traffic',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Návštěvnost',
            'prepend' => '',
            'append' => 'UN',
            'min' => 0,
            'max' => '',
            'step' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'eshop',
        ),
      ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => false,
  ));
    
} );